Resolve issues
QuantEcon/book-dp1 pull request #21
Opened 2023-09-18 04:02 UTC by orectique

Hi @mmcky

The issues #16 , #17 , #18 , #19 , #20 have been resolved. 

The latest version can be found at https://6507c93430d1f5215b8a9c3d--poetic-sprite-e126a3.netlify.app/intro.

2023-09-18 04:09 UTC, mmcky commented on code-book/intro.md
> +# Dynamic Programming <br/> Python and Julia Code
@orectique I think we can remove `Python and Julia Code` from the title as it is redundant (with information below) on the main page

2023-09-18 04:10 UTC, mmcky commented on code-book/_config.yml
> +only_build_toc_files: false
It is usually after to leave the as `true`

then add `status` page to the `toc` to get it to build during compilation. 

I would suggest adding a third section `Other` then list `status` as a page.

2023-09-18 04:10 UTC, mmcky requested changes
@orectique nice work on this. Thanks for the fixes and updates. 

Only a few minor changes requested.

2023-09-21 03:14 UTC, orectique commented
Apologies, @mmcky. I forgot to tag you after pushing the suggested edits.

2023-10-30 00:08 UTC, mmcky approved these changes

2023-10-30 00:09 UTC, merged